src/ratify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'reviews'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ratify/', include(('reviews.urls', app_name), namespace="ratify")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/reviews/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_request, name='login'),

    path('signup/', views.signup, name='signup'),

    path('home/', views.homepage, name='homepage'),

    path('review/<int:review_id>/', views.review_detail, name='review_detail'),

    path('categories/', views.categories, name='categories'),

    path('statistics/', views.statistics, name='statistics'),

    path('statistics/products/', views.get_products, name='get_products'),

    path('statistics/get_statistics_data',
         views.get_statistics_data, name='get_statistics_data'),

    path('addproduct/', views.addproduct, name='addproduct'),

    path('category/<int:cid>/', views.products, name='products'),

    path('category/<int:cid>/<int:pid>/',
         views.product_detail, name='product_detail'),

    path('category/<int:cid>/<int:pid>/add_review/',
         views.add_review, name='add_review'),

    path('review/user/', views.user_review_list, name='user_review_list'),

    path('review/user/<username>/',
         views.user_review_list, name='user_review_list'),

    path('category/<int:cid>/<int:pid>/delete/<int:review_id>/',
         views.delete_review, name='delete_review'),

    path('category/<int:cid>/<int:pid>/Edit/<int:review_id>/',
         views.edit_review, name='edit_review'),


    path('logout/', views.logout_request, name='logout_request'),
]

src/reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
import numpy as np

deleted_choices = [('N', 'No'), ('Y', 'Yes')]


class Category(models.Model):
    catname = models.CharField(unique=True, blank=False, max_length=100)
    # catimg = models.ImageField(upload_to='cat_img', blank=True, null=True)

    def calculate_products(self):
        return self.product_set.count()

    def __str__(self):
        return self.catname + " " + str(self.id)

    class Meta:
        managed = True
        db_table = "Category"


class Product(models.Model):
    pname = models.CharField(max_length=30, blank=False)
    company = models.CharField(max_length=30)  # one category has many products
    price = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_by = models.CharField(max_length=25)
    website = models.CharField(max_length=25, null=True)
    is_deleted = models.CharField(
        max_length=1, choices=deleted_choices, default='N')
    created_on = models.DateTimeField(auto_now_add=True, blank=True)
    modified_on = models.DateTimeField(auto_now=True, blank=True, null=True)
    specification = models.TextField(max_length=200, null=True)
    pimg = models.ImageField(upload_to='prod_img', blank=True, null=True)

    def average_rating(self):
        all_ratings = map(lambda x: x.rating, self.review_set.all())
        return np.mean(list(all_ratings))

    def total_rating(self):
        return self.review_set.count()

    def __str__(self):
        return self.pname + "" + str(id)

    class Meta:
        managed = True
        db_table = "Product"


class Appuser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    is_deleted = models.CharField(
        max_length=1, choices=deleted_choices, default='N')
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+91'. Up to 15 digits allowed.")
    is_deleted = models.CharField(
        max_length=1, choices=deleted_choices, default='N')
    mobile = models.CharField(
        validators=[phone_regex], max_length=12, blank=True, null=True)

    def calculate_reviews(self):
        return self.review_set.count()

    def __str__(self):
        return self.user.username

    class Meta:
        managed = True
        db_table = "Appuser"


class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    rated_by = models.ForeignKey(Appuser, on_delete=models.CASCADE)
    comment = models.TextField(max_length=300)
    is_deleted = models.CharField(
        max_length=1, choices=deleted_choices, default='N')
    rating = models.IntegerField(choices=RATING_CHOICES)
    pub_date = models.DateTimeField('date published')
    upvote = models.IntegerField(
        name='upvote', blank=True, null=True, default=0)
    downvote = models.IntegerField(
        name='downvote', blank=True, null=True, default=0)

    def increment_upvote(self):
        self.upvote += 1

    def decrement_downvote(self):
        self.downvote += 1

    def __str__(self):
        return self.product.pname + " by " + self.rated_by.user.username

    class Meta:
        managed = True
        db_table = "Review"

src/reviews/forms.py
from django import forms
from .models import *
from django.forms import Textarea
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    email = forms.EmailField(
        max_length=254)
    password2 = forms.CharField(widget=forms.PasswordInput(
    ), label='Confirm')

    def clean_username(self):
        username = self.cleaned_data['username']
        r = User.objects.filter(username=username)
        if r.count():
            raise forms.ValidationError("Username already exists")
        return username

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Password don't match")
        return password2

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise forms.ValidationError("Email already exists")
        return email

    class Meta:
        model = User
        fields = ('email', 'username', 'first_name', 'last_name')


class Appuserform(forms.ModelForm):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+91'. Up to 15 digits allowed.")
    mobile = forms.CharField(max_length=12, min_length=10, validators=[
                             phone_regex], widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Appuser
        fields = ['mobile']


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['pimg', 'pname', 'company', 'price',
                  'category', 'website', 'specification']


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }

src/reviews/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import messages
from .forms import UserForm, Appuserform, AddProductForm, ReviewForm
from django.contrib.auth.models import User
from .models import *
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.storage import FileSystemStorage
import datetime
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

# Create your views here.


def login_request(request):
    if request.method == 'POST':
        _username = request.POST.get('username')
        _password = request.POST.get('password')
        print(_username)
        print(_password)

        try:
            us = User.objects.get(username=_username)
            print(us)
            login(request, us)
            if us is not None:
                # return HttpResponse("You have successfully signed in !!")
                # messages.success(
                #    request, f"You are now logged in as {request.user.username}")
                return redirect('/ratify/home')
            else:
                messages.error(request, 'The form is invalid.')
        except User.DoesNotExist:
            messages.error(request, 'The form is invalid.')

        # uu = authenticate(username=_username, password=_password)
        # print(uu)

    return render(request, "reviews/login.html")


def signup(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        appuserform = Appuserform(request.POST)

        if user_form.is_valid() and appuserform.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            app_user = appuserform.save(commit=False)
            app_user.user = user
            app_user.save()
            login(request, user)
            return redirect('/ratify/home/')
        else:
            print(user_form.errors)
            print(appuserform.errors)
            messages.error(request, user_form.errors)
            messages.error(request, appuserform.errors)
            return redirect('/ratify/signup')

    else:
        userform = UserForm()
        userform1 = Appuserform()
        return render(request, 'reviews/signup.html', {'userform': userform, 'userform1': userform1})


def homepage(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:10]
    top_products = []
    allproducts = Product.objects.all()

    for prod in Product.objects.all():
        if prod.average_rating() >= 3:
            top_products.append(prod)

    return render(request, 'reviews/homepage.html', {'latest_review_list': latest_review_list, 'top_products': top_products})


@csrf_exempt
def get_products(request):
    products = Product.objects.filter(
        category_id=request.POST.get('category_id', ''))
    product_obj = serializers.serialize('python', products)
    return JsonResponse(product_obj, safe=False)


@csrf_exempt
def get_statistics_data(request, *args, **kwargs):
    labels = []
    data = []

    catid = request.POST.get('cat', '')

    products = Product.objects.filter(category_id=catid)

    for p in products:
        labels.append(p.pname)
        data.append(p.total_rating())

    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})


def user_review_list(request, username=None):
    user = None
    if not username:
        user = request.user
    else:
        user = User.objects.get(username=username)

    appuser = Appuser.objects.get(user=user)
    latest_review_list = Review.objects.filter(
        rated_by=appuser, is_deleted='N').order_by('-pub_date')

    nop = Product.objects.filter(created_by=username).count()

    context = {
        'nop': nop,
        'latest_review_list': latest_review_list,
        'username': user.username,
        'appuser': appuser

    }
    return render(request, 'reviews/user_review_list.html', context)


def categories(request):
    categories = Category.objects.all()
    return render(request, 'reviews/categories.html', {'categories': categories})


def statistics(request):
    categories = Category.objects.all()
    return render(request, 'reviews/statistics.html', {'categories': categories})


def addproduct(request):
    if request.method == 'POST':
        pform = AddProductForm(request.POST, request.FILES)
        if pform.is_valid():
            data = pform.cleaned_data
            img = data["pimg"]
            print(img)
            product = pform.save(commit=False)
            product.created_by = request.user.username
            product.save()
            return redirect('/ratify/home/')

            '''
            pname = request.POST['pname']
            company = request.POST['company']
            price = request.POST['price']
            cat = request.POST['category']
            category = Category.objects.get(catname=cat)
            website = request.POST['website']
            specification = request.POST['speci']
            data = pform.cleaned_data
            image = data["pimg"]
            print(image)
            print()

            if image != None:
                product = Product(pname=pname, company=company, price=price, category=category, website=website,
                                  specification=specification, pimg=image, created_by=request.user.username)
                # product.save()

                fs = FileSystemStorage()
                filename = fs.save(image.name, image)

                uploaded_file_url = fs.url(filename)
                print(uploaded_file_url)

            else:
                pass'''
        else:
            print('hi')
            categories = Category.objects.all()
            pform = AddProductForm()
            return render(request, 'reviews/addproduct.html', {'categories': categories, 'pform': pform})

    else:
        categories = Category.objects.all()
        pform = AddProductForm()
        return render(request, 'reviews/addproduct.html', {'categories': categories, 'pform': pform})


def products(request, cid):
    products = Product.objects.filter(category_id=cid)
    category = Category.objects.get(pk=cid)
    return render(request, 'reviews/products.html', {'products': products, 'category': category})


def product_detail(request, cid, pid):
    product = Product.objects.get(pk=pid, category_id=cid)
    category = Category.objects.get(id=cid)
    form = ReviewForm()
    return render(request, 'reviews/product_detail.html', {'product': product, 'form': form, 'category': category})


def add_review(request, cid, pid):
    product = Product.objects.get(pk=pid, category_id=cid)
    category = Category.objects.get(pk=cid)
    appuser = Appuser.objects.get(user=request.user)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            rating = form.cleaned_data['rating']
            comment = form.cleaned_data['comment']
            review = Review()
            review.product = product
            review.category = category
            review.rated_by = appuser
            review.rating = rating
            review.comment = comment
            review.pub_date = datetime.datetime.now()
            review.save()
            return HttpResponseRedirect(reverse('reviews:product_detail', args=(category.id, product.id, )))

    form = ReviewForm()
    return render(request, 'reviews/product_detail.html', {'product': product, 'form': form, 'category': category})


def edit_review(request, cid, pid, review_id):
    product = Product.objects.get(pk=pid, category_id=cid)
    category = Category.objects.get(pk=cid)
    review = Review.objects.get(pk=review_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('reviews:product_detail', args=(category.id, product.id, )))
    else:
        form = ReviewForm(instance=review)
        return render(request, 'reviews/review_edit.html', {'form': form, 'category': category, 'product': product, 'review': review})


def delete_review(request, cid, pid, review_id):
    review = get_object_or_404(Review, pk=review_id)
    review.is_deleted = 'Y'
    review.save()
    return HttpResponseRedirect(reverse('reviews:product_detail', args=(cid, pid, )))


def logout_request(request):
    logout(request)
    return redirect('/ratify/login')

src/reviews/templates/reviews/addproduct.html
{% extends 'reviews/base.html' %} 
{% load static %}

{% block title %}Add Product{% endblock %} 

{% block content %}



        <link rel="stylesheet" type="text/css" href="{% static 'reviews/categories/Grid.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'reviews/addProduct/addProduct.css' %}">

        <section class="register-page">
            <div class="form">
              <form class="register-form" action="{% url 'reviews:addproduct' %}" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
          
                    <div>
                    
                
                  
                  {{pform.as_p }}
                  <!--<input type="file" name="pimg" onchange="previewFile()">-->

                </div>
                <!--<div class="col span-1-of-2">
                  <input type="text" name="pname" placeholder="Product name" required />
                    <input type="text" name="company" placeholder="Company" required />
                    <input type="text" name="website" placeholder="website" required />
                    <select id="category" name="category" title="Categories" required>
                            <option selected>--select--</option>
                                {% for category in categories %}
                                    <option>{{category.catname}}</option>
                                {% endfor %}
                    </select>
                    <input type="text" name="price" placeholder="Price"required />
                    <textarea  name="speci" placeholder="Specifications" required></textarea>
                </div>-->
                <button type="submit">create</button>
                </div>
                
              </form>
            </div>
          </div>
           <script src="{% static 'reviews/addProduct/addProduct.js' %}"></script>
        </section>
    


{% endblock %}


        

src/reviews/templates/reviews/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900"
      rel="stylesheet"
    />

    <!--<link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    />-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>

    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>

    <link
      rel="stylesheet"
      href="{% static 'reviews/homepage/style.css' %}"
      type="text/css"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav>
      <div class="row__main-nav clearfix">
        <ul class="main-nav">
          <li>
            <a href="{% url 'reviews:homepage' %}">Ratify</a>
            <a href="{% url 'reviews:categories' %}">Categories</a>
            <a href="{% url 'reviews:statistics' %}">Statistics</a>
            <a href="{% url 'reviews:logout_request' %}">Logout</a>
            <a href="{% url 'reviews:addproduct' %}">Add Product</a>
          </li>
        </ul>
        <a
          class="btn"
          href="{% url 'reviews:user_review_list' request.user.username %}"
        >
          <h3>{{request.user.username}}</h3>
        </a>
      </div>
    </nav>

    <div>
      {% block content %}
      <!--All extended template's content will be placed here-->
      {% endblock %}
    </div>
  </body>
</html>

src/reviews/templates/reviews/login.html
{% load static %} {% load bootstrap3 %} {% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    {% bootstrap_css %} {% bootstrap_javascript %}
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="{% static 'reviews/login/login.css' %}"
      type="text/css"
    />

    <title>Login</title>
  </head>
  <body>
    <div class="login-page">
      <div class="form">
        <form class="login-form" method="post">
          {% csrf_token %}

          <input name="username" type="text" placeholder="username" />
          <input name="password" type="password" placeholder="password" />

          <button>login</button>
          <p class="message">
            Not registered?
            <a href="{% url 'reviews:signup' %}">Create an account</a>
          </p>
        </form>
      </div>
    </div>
  </body>
</html>

src/reviews/templates/reviews/product_detail.html
{% extends 'reviews/base.html' %}
{% load static %} 
{% block title %}Product Detail{%endblock %} 

{% block content %}

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'reviews/ProductDetail/productdetail.css' %}"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'reviews/categories/Grid.css' %}"
    />

    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>

     <section class="section-product-info">
            <div class="row">
                <div class="col span-1-of-3">
                    <img src="{{product.pimg.url}}" alt="error" class="product-img">
                </div>
                <div class="col span-2-of-3 product-details">
                    <h2>{{product.pname}} </h2>
                         <h3 style="float: right;display: inline; color: black;">
                            Reviews: <span class="product-value">{{product.review_set.count}}</span><br>
                            Average Rating: <span class="product-value">{{product.average_rating | floatformat}}</span>
                        </h3> 
                    <h4>Price: <span class="product-value">{{product.price | floatformat}}</span> Rs</h4>
                    <h4>Description:</h4>
                    <p>{{product.specification}}</p>
                </div>
            </div>
        </section>
        <section class="section-reviews">
            <div class="row reviews">
                <h2>Recent Reviews</h2>

                {% if product.review_set.all %}
                    <div class="comment-box">
                        {% for review in product.review_set.all %}

                        {% if review.is_deleted == 'N' %}
                            <div class="comment-body">
                                
                                {% if request.user.username == review.rated_by.user.username %}

                                    <a href="{% url 'reviews:edit_review' cid=category.id pid=product.id review_id=review.id %}">
                                        <div class="edit-review">                                
                                            <ion-icon name="create-outline"></ion-icon>
                                        </div>
                                    </a>
                                    <a href="{% url 'reviews:delete_review' cid=category.id pid=product.id review_id=review.id %}">
                                        <div class="delete-review">
                                            <ion-icon name="trash-outline"></ion-icon>
                                        </div>
                                    </a>

                                {% endif %}



                                    <div class="product-rating">
                                        <h4>Rated <span class="value">{{ review.rating }} of 5 </span> by <a href="{% url 'reviews:user_review_list' review.rated_by.user.username %}" >{{ review.rated_by.user.username }}</a></h4>
                                    </div>
                                    <div class="mail-content">
                                        <span class="mail-desc">{{ review.comment }}</span>
                                        <br>
                                        <div class="user-details">
                                            <h5>{{ review.rated_by.username }}</h5>
                                            <span class="time">{{ review.pub_date }}</span>
                                        </div>
                                        <!--<div class="rating-buttons">
                                            <a href="#"><ion-icon name="thumbs-up-outline" class="upvote"></ion-icon></a>
                                            <a href="#"><ion-icon name="thumbs-down-outline"  class="downvote"></ion-icon></a>
                                        </div>-->
                                    </div>
                                </div>
                        {% endif %}
                            
                            
                        {% endfor %}
                        
                    </div>

                {% else %}
                    <p>No reviews for this product yet</p>
                {% endif %}


                    <div>
                        <div class="row">
                            <h2>Add Review</h2>
                        </div>
                        <form action="{% url 'reviews:add_review' cid=category.id pid=product.id  %}" method="post" class="form">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit">Add</button>
                        </form>
                   </div>
            </div>
        </section>
        

</div>

{% endblock %}

src/reviews/templates/reviews/statistics.html
{% extends 'reviews/base.html' %} 
{% load static %}

{% block title %}Statistics{% endblock %} 



{% block content %}


    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
        <link rel="stylesheet" type="text/css"  href="{% static 'reviews/categories/Grid.css' %}">

            <link rel="stylesheet" type="text/css" href="{% static 'reviews/statistics.css' %}" />





<script type="text/javascript">
    $(document).ready(()=>{

        var cat;
    

        $("select#category").change(function(){
            var category_id = $(this).val();
            var categoryvalue = $('#category :selected').text();
            console.log(category_id);
            console.log(categoryvalue);

            cat = category_id;

            /*$('#product').prop("hidden", false);

            var opt = "";
            fetchProducts(category_id);

            $("select#product").html('<option selected>--select--</option>');

            function fetchProducts(category_id){
                $.ajax({
                    url:'{% url 'reviews:get_products' %}',
                    type: 'POST',
                    data:{category_id:category_id},
                })
                .done(function(response){
                    for(key in response){
                        console.log(response[key]['fields']['pname']);

                        opt = "<option value='" + response[key]['pk'] + "'>" + response[key]['fields']['pname'] +"</option>";
                        $("select#product").append(opt);
                    }
                })
                .fail(function(){
                    console.log("Failed");
                    alert("Select Category");
                });
            }*/

        });


    
        $("#viewchart").click(function(){

            

             $(function() {
                $.ajax({
                    url: '{% url 'reviews:get_statistics_data' %}',
                    type: 'POST',
                    data:{cat:cat},
                })
                .done(function(data){
                    console.log("Success");
                    console.log(data);

                    var ctx = document.getElementById('review-chart').getContext('2d');

                    new Chart(ctx, {
                        type: 'bar',
                        data: {
                              labels: data.labels,
                              datasets: [{
                                label: 'Total rating',
                                backgroundColor: 'blue',
                                data: data.data
                              }]
                        },
                        options: {
                          responsive: true,
                          legend: {
                            position: 'top',
                          },
                          title: {
                            display: true,
                            text: 'Reviews Bar Chart'
                          }
                        }
                    });
                })
                .fail(function(){
                    console.log("Failed");
                    alert("No data Available");
                });
             });

        });

    });
</script>









<section >
            <div class="row">
                <div class="form">
                    <form class="register-form">
                        <div class="row">
                            <div class="col span-1-of-2">
                            
                            <label for="sel1" class="lables">Choose Category</label>
                                <select name="category" id="category" title="Categories">
                                     <option selected>--select--</option>
                                            {% for category in categories %}
                                                <option id="{{category.id}}" value="{{ category.id }}">{{category.catname}}</option>
                                            {% endfor %}
                                </select>
                            </div>
                         
                            <div class="col span-1-of-2">
                            
                                <input type="button" id="viewchart" class="btn pull-right" value="View Chart" style="margin-top: 2.7rem; background-color: #2998ff;;  border:2px solid rgb(50, 50, 95);">
                            </div>
                        </div>
                        <!--<div class="row chart-space"></div>-->
                                  
                    </form>
                    
                </div>
            </div>
            <div id="container" style="width: 90%; height: 50%; ">
                <canvas id="review-chart"></canvas>
            </div>
          </div>
        </section>


</div>

{% endblock %}